server:
  port: ${APPLICATION_PORT:8080}

kafka:
  topics:
    commands: commands
    queries: queries
    events: events

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: chat-consumers
      auto-offset-reset: earliest