server:
  port: ${APPLICATION_PORT:8080}

kafka:
  topics:
    commands: "commands"
    queries: "queries"

spring:
  kafka:
    bootstrap-servers: "localhost:29092"
    consumer:
      group-id: "chat-consumers"
      auto-offset-reset: earliest